In [1]:
import numpy as np

In [3]:
list1 = [1, 2, 3]
print('list type', type(list1))
array1 = np.array(list1)
#array1 = np.array([1, 2, 3])
print('array1 type', type(array1))
print('array1 array 형태', array1.shape)

array2 = np.array([[1, 2, 3],
                  [2, 3, 4]])
print('array2 type', type(array2))
print('array2 array 형태', array2.shape)

array3 = np.array([[1, 2, 3]])
print('array3 type', type(array3))
print('array3 array 형태', array3.shape)


list type <class 'list'>
array1 type <class 'numpy.ndarray'>
array1 array 형태 (3,)
array2 type <class 'numpy.ndarray'>
array2 array 형태 (2, 3)
array3 type <class 'numpy.ndarray'>
array3 array 형태 (1, 3)


#### ndarray 의 데이터 타입

In [4]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [6]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [9]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64') # array_int.astype(np.float64)
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [12]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [15]:
#(3, 2) shape를 가지는 모든 원소가 0, dtype은 int32인 ndarray 생성
zero_array = np.zeros((3, 2))
print(zero_array)
print(zero_array.dtype, zero_array.shape)

#{3, 2} shape를 가지는 모든 원소가 1인 ndarray 생성.
one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)


[[0. 0.]
 [0. 0.]
 [0. 0.]]
float64 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### ndarray의 차원과 크기를 변경하는 reshape

In [18]:
array1 = np.arange(10)
print('array1:\n', array1)

#(2, 5) shape로 변환
array2 = array1.reshape(2, 5)
print('array2:\n', array2)

#(5, 2) shape로 변환
array3 = array1.reshape(5, 2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


### 넘파이 ndarray의 데이터 세트 선택하기 - indexing

- 단일 인덱싱

In [19]:
# 1에서부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1', array1)
# index 는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value', value)
print(type(value))

array1 [1 2 3 4 5 6 7 8 9]
value 3
<class 'numpy.int32'>


In [20]:
print('맨 뒤의 값', array1[-1], ', 맨 뒤에서 두번째 값:', array1[-2])

맨 뒤의 값 9 , 맨 뒤에서 두번째 값: 8


In [21]:
array1[0] = 9
array1[8] = 0
print('array1', array1)

array1 [9 2 3 4 5 6 7 8 0]


In [22]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

print('(row=0, col=0) index 가리키는 값', array2d[0,0])
print('(row=0, col=1) index 가리키는 값', array2d[0,1])
print('(row=1, col=0) index 가리키는 값', array2d[1,0])
print('(row=2, col=2) index 가리키는 값', array2d[2,2])

(row=0, col=0) index 가리키는 값 1
(row=0, col=1) index 가리키는 값 2
(row=1, col=0) index 가리키는 값 4
(row=2, col=2) index 가리키는 값 9


- 슬라이싱 인덱싱